 CREATE TABLE `a7508574_gal`.`advcomments` (
`id` INT NOT NULL AUTO_INCREMENT ,
`imgid` INT NOT NULL ,
`Nick` TEXT NOT NULL ,
`Mail` TEXT NOT NULL ,
`Web` TEXT NULL ,
`Text` TEXT NOT NULL ,
`date` DATE NOT NULL ,
`stat` INT NOT NULL ,
PRIMARY KEY ( `id` )
) ENGINE = MYISAM 